mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('taskmaster.urls')),
    path('admin/', admin.site.urls),
]

handler404 = 'taskmaster.views.error404'

taskmaster/urls.py
from django.urls import path
from .views import HomeView, TaskCreateView, TasksDeleteView, LoginView, RegisterView, ProjectListView, ProjectCreateView, ProjectDeleteView, ProjectUpdateView, TaskUpdateStatus, TaskUpdateView, ProjectDetailView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('projects/', ProjectListView.as_view(), name='project_list'),
    path('projects/tasks/<int:pk>', ProjectDetailView.as_view(), name='task_list'),
    path('projects/tasks/<int:pk>/status/<str_status>', TaskUpdateStatus.as_view(), name='task_status'),
    path('tasks/create/', TaskCreateView.as_view(), name='task_create'),
    path('tasks/delete/<pk>', TasksDeleteView.as_view(), name='tasks_delete'),
    path('projects/tasks/update/<pk>', TaskUpdateView.as_view(), name='task_update'),
    path('projects/delete/<pk>', ProjectDeleteView.as_view(), name='project_delete'),
    path('projects/update/<pk>', ProjectUpdateView.as_view(), name='project_update'),
    path('projects/create/', ProjectCreateView.as_view(), name='project_create'),
]

taskmaster/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owned_projects")
    collaborators = models.ManyToManyField(User, related_name="collaborated_projects", blank=True)

    def __str__(self):
        return self.title
    
    def total_tasks(self):
        return self.tasks.count()
    
    def total_tasks_done(self):
        return self.tasks.filter(status='DONE').count()


class Task(models.Model):
    STATUS_CHOICES = [
        ("TODO", "Pendiente"),
        ("IN_PROGRESS", "En Progreso"),
        ("DONE", "Completada")
    ]

    PRIORITY_CHOICES = [
        ("L", "Baja"),
        ("M", "Media"),
        ("H", "Alta")
    ]

    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='tasks', null=False, blank=False)
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=255, choices=STATUS_CHOICES, default="TODO")
    priority = models.CharField(max_length=255, choices=PRIORITY_CHOICES, default="M")
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.title} ({self.project.title})"
    
    def save(self, *args, **kwargs):
        print("TASK SAVE", self.pk)
        super().save(*args, **kwargs)

taskmaster/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, ListView, CreateView, DeleteView, UpdateView, DetailView
from .models import Project, Task
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.utils import timezone
from django.db.models import Q
from django.conf import settings

# Create your views here.
def error404(request, exception):
    # Nos permite personalizar la página del error 404
    return render(request, '404.html')

class HomeView(View):
    # Clase que muestra la página de inicio
    template_name = "home.html"

    def get(self, request):
        # Nos permite visualizar la página
        return render(request, self.template_name)

class ProjectListView(LoginRequiredMixin, ListView):
    # Clase que muestra los proyectos del usuario y en los que colabora
    model = Project
    template_name = "project_list.html"
    context_object_name = "projects"
    login_url = '/login/'

    def get_queryset(self):
        # Mostramos los proyectos del usuario y en los que colabore
        return Project.objects.filter(Q(owner=self.request.user) | Q(collaborators=self.request.user)).order_by("deadline")

class ProjectForm(forms.ModelForm):
    # Clase que crea los formularios de los proyectos
    class Meta:
        model = Project
        fields = ['title', 'description', 'deadline', 'collaborators']
        widgets = {'deadline': forms.DateInput(attrs={'type': 'date'})}
    
    def __init__(self, *args, **kwargs):
        # Cogemos al usuario
        self.user = kwargs.pop('user', None)
        super(ProjectForm, self).__init__(*args, **kwargs)

        # Si tenemos al usuario, lo quitamos de los colaboradores
        if self.user:
            self.fields['collaborators'].queryset = User.objects.exclude(id=self.user.id)
    
    def clean_collaborators(self):
        # Si aún asi se muestra el usuario, que no se pueda escoger como colaborador
        collaborators = self.cleaned_data.get('collaborators')
        if self.user in collaborators:
            raise forms.ValidationError("No puedes ser colaborador y creador a la vez")
        else:
            return collaborators

    def clean_deadline(self):
        # Comprobamos que la fecha no sea anterior a la actual
        deadline = self.cleaned_data.get('deadline')
        if deadline < timezone.now().date():
            raise forms.ValidationError("No puede ser una fecha pasada")
        else:
            return deadline

class ProjectCreateView(LoginRequiredMixin, CreateView):
    # Clase que crea los proyectos
    model = Project
    template_name = "project_create.html"
    form_class = ProjectForm
    success_url = '/projects/'
    login_url = '/login/'

    def get_form_kwargs(self):
        # Recogemos los datos del formulario
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        # Validamos el formulario
        form.instance.owner = self.request.user
        return super().form_valid(form)

class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    # Clase que elimina los proyectos
    model = Project
    template_name = "confirm_delete.html"
    success_url = '/projects/'
    login_url = '/login/'

class ProjectUpdateView(LoginRequiredMixin, UpdateView):
    # Clase que actualiza los proyectos
    model = Project
    template_name = "project_update.html"
    form_class = ProjectForm
    success_url = "/projects/"
    login_url = '/login/'

    def get_form_kwargs(self):
        # Recogemos los datos del formulario
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class ProjectDetailView(LoginRequiredMixin, DetailView):
    # Clase que muestra el detalle de los proyectos (tareas asociadas)
    model = Project
    template_name = "task_list.html"
    context_object_name = "project"
    login_url = '/login/'
    
    def get_context_data(self, **kwargs):
        # Recogemos los datos para mostrarlos
        context = super().get_context_data(**kwargs)
        project = self.object
        
        context['tasks'] = project.tasks.order_by("project__deadline")
        total = project.tasks.count()
        context['total_tasks'] = total
        if total > 0:
            # Para que no nos de un error de división entre 0
            context['done_tasks'] = project.tasks.filter(status='DONE').count() * 100 / project.tasks.count()
        else:
            context['done_tasks'] = 0
        context['labels'] = ["Completadas", "No completadas"]
        return context

class TaskForm(forms.ModelForm):
    # Clase que crea los formularios de las tareas
    class Meta:
        model = Task
        fields = ['project', 'title', 'description', 'status', 'priority', 'assigned_to']
    
    def __init__(self, *args, **kwargs):
        # Cogemos al usuario
        self.user = kwargs.pop('user', None)
        super(TaskForm, self).__init__(*args, **kwargs)

        self.fields['description'].required = False

        # Quitamos los que no son ni propietarios ni colaboradores
        if self.user:
            self.fields['project'].queryset = Project.objects.filter(Q(owner=self.user) | Q(collaborators=self.user)).distinct()
            self.fields['assigned_to'].queryset = User.objects.filter(Q(owned_projects__in=self.fields['project'].queryset) | Q(collaborated_projects__in=self.fields['project'].queryset)).distinct()
        
    def clean(self):
        cleaned_data = super().clean()
        project = cleaned_data.get('project')
        assigned_to = cleaned_data.get('assigned_to')

        if project and assigned_to:
            # Verificamos que el usuario asignado sea el creador o un colaborador
            is_owner = (project.owner == assigned_to)
            is_collaborator = project.collaborators.filter(id=assigned_to.id).exists()

            if not is_owner and not is_collaborator:
                raise forms.ValidationError("No puedes asignarle la tarea a alguien que no sea el creador o colaborador")

class TaskCreateView(LoginRequiredMixin, CreateView):
    # Clase que crea las tareas
    model = Task
    template_name = "task_create.html"
    form_class = TaskForm
    login_url = '/login/'

    def get_form_kwargs(self):
        # Recogemos los datos del formulario
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def get_success_url(self):
        # Volvemos a la página justo anterior
        return f'/projects/tasks/{self.object.project.id}'

    def form_valid(self, form):
        # Validamos el formulario
        return super().form_valid(form)
    
class TasksDeleteView(LoginRequiredMixin, DeleteView):
    # Clase que elimina las tareas
    model = Task
    template_name = "confirm_delete.html"
    login_url = '/login/'

    def get_success_url(self):
        # Volvemos a la página justo anterior
        return f'/projects/tasks/{self.object.project.id}'

class TaskUpdateStatus(LoginRequiredMixin, View):
    # Clase que actualiza el estado de las tareas
    login_url = '/login/'

    def post(self, request, pk, str_status):
        # Actualizamos el estado de la tarea
        task = get_object_or_404(Task, pk=pk)
        if not (task.project.owner == request.user or task.project.collaborators.filter(id=request.user.id).exists()):
            # Si el usuario no es el creador o un colaborador, no lo puede modificar
            return redirect('/projects/')
        task.status = str_status
        task.save()
    
        return redirect(request.META.get('HTTP_REFERER', '/projects/'))

class TaskUpdateView(LoginRequiredMixin, UpdateView):
    # Clase que actualiza las tareas
    model = Task
    template_name = "task_update.html"
    form_class = TaskForm
    login_url = '/login/'

    def get_form_kwargs(self):
        # Recogemos los datos del formulario
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def get_success_url(self):
        # Volvemos a la página justo anterior
        return f'/projects/tasks/{self.object.project.id}'

class AnonymousMixin(UserPassesTestMixin):
    # Clase que verifica que el usuario no ha iniciado sesión
    def test_func(self):
        return not self.request.user.is_authenticated
    
    def handle_no_permission(self):
        return redirect('/tasks/')

class LoginView(AnonymousMixin, auth_views.LoginView):
    # Clase que muestra la página de inicio de sesión
    template_name = 'registration/login.html'

class RegisterView(AnonymousMixin, CreateView):
    # Clase que muestra la página de registro y crea las cuentas de usuario
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = '/login/'

taskmaster/templates/confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar Eliminación</title>
    <link rel="stylesheet" href="{% static 'css/styles_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles_delete.css' %}">
</head>
<body class="body">
    <main class="main">
        <h2 class="main__title">¿Estás seguro de que quieres eliminarlo?</h2>
        <form class="main__form" method="post">
            {% csrf_token %}
            <button class="form__btn form__accept" type="submit">Sí, Eliminar</button>
            <a class="form__btn form__cancel" href="javascript:history.back()">Cancelar</a>
        </form>
    </main>
</body>
</html>

taskmaster/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bienvenida</title>
    <link rel="stylesheet" href="{% static 'css/styles_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles_home.css' %}">
</head>
<body class="body">
    <main class="main">
        <h1 class="main__title">Bienvenido a Taskmaster</h1>
        <a class="main__link" href="{% url 'project_list' %}">COMENZAR</a>
    </main>
</body>
</html>

taskmaster/templates/project_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Proyecto</title>
    <link rel="stylesheet" href="{% static 'css/styles_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles_form.css' %}">
</head>
<body class="body">
    <header class="header">
        <nav class="nav">
            <a class="nav__link" href="{% url 'home' %}">Inicio</a>
            <a class="nav__link" href="{% url 'project_list' %}">Mis Proyectos</a>
            <a class="nav__link" href="{% url 'project_create' %}">Crear Nuevo Proyecto</a>
            <a class="nav__link" href="{% url 'task_create' %}">Crear Nueva Tarea</a>
            <form id="logout-form" method="post" action="/logout/">
                {% csrf_token %}
                <button class="nav__link btn__session" type="submit">Cerrar Sesión</button>
            </form>
        </nav>
    </header>

    <main class="main">
        <h1 class="main__title">Crear Nuevo Proyecto</h1>
        <form class="main__form" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="form__btn" type="submit">Crear Proyecto</button>
        </form>
    </main>

    <section class="back">
        <a class="back__link" href="javascript:history.back()">VOLVER</a>
    </section>
</body>
</html>

taskmaster/templates/project_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Proyectos</title>
    <link rel="stylesheet" href="{% static 'css/styles_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles_project_list.css' %}">
</head>
<body class="body">
    <header class="header">
        <nav class="nav">
            <a class="nav__link" href="{% url 'home' %}">Inicio</a>
            <a class="nav__link" href="{% url 'project_list' %}">Mis Proyectos</a>
            <a class="nav__link" href="{% url 'project_create' %}">Crear Nuevo Proyecto</a>
            <a class="nav__link" href="{% url 'task_create' %}">Crear Nueva Tarea</a>
            <form id="logout-form" method="post" action="/logout/">
                {% csrf_token %}
                <button class="nav__link btn__session" type="submit">Cerrar Sesión</button>
            </form>
        </nav>
    </header>

    <main class="main">
        <section class="main__owner">
            <h1 class="owner__title">Mis Proyectos</h1>
            <div class="owner_projects">
                <!-- Mostramos los proyectos que ha creado el usuario -->
                {% for project in user.owned_projects.all|dictsort:"deadline" %}
                    <article class="projects__project">
                        <h2>{{ project.title }}</h2>
                        <p>Descripción: {{ project.description }}</p>
                        <p>Creado en: {{ project.created_at }}</p>
                        <p>Fecha límite: {{ project.deadline }}</p>
                        <p>Creador: {{ project.owner }}</p>
                        <p>Colaboradores: 
                            <!-- Mostramos los colaboradores del proyecto -->
                            {% for collaborator in project.collaborators.all %}
                                {{ collaborator }} 
                            {% empty %}
                                No hay colaboradores
                            {% endfor %}
                        </p>
                        <a class="project__link" href="{% url 'task_list' project.id %}">Hay {{ project.total_tasks }} tareas asignadas</a>
                        <p>Hay {{ project.total_tasks_done }} tareas completadas</p>
                        <div class="project__actions">
                            <form action="/projects/update/{{ project.id }}" method="get">
                                {% csrf_token %}
                                <button class="project__btn project__update" type="submit">Editar Proyecto</button>
                            </form>
                            <form action="/projects/delete/{{ project.id }}" method="get">
                                {% csrf_token %}
                                <button class="project__btn project__delete" type="submit">Eliminar Proyecto</button>
                            </form>
                        </div>
                    </article>
                {% endfor %}
            </div>
        </section>

        <section class="main__collaborators">
            <h1 class="collaborators__title">Colaboraciones</h1>
            <div class="collaborators__projects">
                <!-- Mostramos los proyectos en los que colabora el usuario -->
                {% for project in user.collaborated_projects.all|dictsort:"deadline" %}
                    <article>
                        <h2>{{ project.title }}</h2>
                        <p>Descripción: {{ project.description }}</p>
                        <p>Creado en: {{ project.created_at }}</p>
                        <p>Fecha límite: {{ project.deadline }}</p>
                        <p>Creador: {{ project.owner }}</p>
                        <!-- Mostramos los colaboradores del proyecto -->
                        <p>Colaboradores: 
                            {% for collaborator in project.collaborators.all %}
                                {{ collaborator }} 
                            {% empty %}
                                No hay colaboradores
                            {% endfor %}
                        </p>
                        <a class="project__link" href="{% url 'task_list' project.id %}">Hay {{ project.total_tasks }} asignadas</a>
                        <p>Hay {{ project.total_tasks_done }} tareas completadas</p>
                    </article>
                {% endfor %}
            </div>
        </section>
    </main>
</body>
</html>

taskmaster/templates/project_update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar Proyecto</title>
    <link rel="stylesheet" href="{% static 'css/styles_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles_form.css' %}">
</head>
<body class="body">
    <header class="header">
        <nav class="nav">
            <a class="nav__link" href="{% url 'home' %}">Inicio</a>
            <a class="nav__link" href="{% url 'project_list' %}">Mis Proyectos</a>
            <a class="nav__link" href="{% url 'project_create' %}">Crear Nuevo Proyecto</a>
            <a class="nav__link" href="{% url 'task_create' %}">Crear Nueva Tarea</a>
            <form id="logout-form" method="post" action="/logout/">
                {% csrf_token %}
                <button class="nav__link btn__session" type="submit">Cerrar Sesión</button>
            </form>
        </nav>
    </header>

    <main class="main">
        <h1 class="main__title">Actualizar Proyecto</h1>
        <form class="main__form" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="form__btn" type="submit">Actualizar Proyecto</button>
        </form>
    </main>

    <section class="back">
        <a class="back__link" href="{% url 'project_list' %}">VOLVER</a>
    </section>
</body>
</html>

taskmaster/templates/task_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Tarea</title>
    <link rel="stylesheet" href="{% static 'css/styles_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles_form.css' %}">
</head>
<body class="body">
    <header class="header">
        <nav class="nav">
            <a class="nav__link" href="{% url 'home' %}">Inicio</a>
            <a class="nav__link" href="{% url 'project_list' %}">Mis Proyectos</a>
            <a class="nav__link" href="{% url 'project_create' %}">Crear Nuevo Proyecto</a>
            <a class="nav__link" href="{% url 'task_create' %}">Crear Nueva Tarea</a>
            <form id="logout-form" method="post" action="/logout/">
                {% csrf_token %}
                <button class="nav__link btn__session" type="submit">Cerrar Sesión</button>
            </form>
        </nav>
    </header>

    <main class="main">
        <h1 class="main__title">Crear Nueva Tarea</h1>
        <form class="main__form" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="form__btn" type="submit">Crear Tarea</button>
        </form>
    </main>

    <section class="back">
        <a class="back__link" href="javascript:history.back()">VOLVER</a>
    </section>
</body>
</html>

taskmaster/templates/task_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tareas</title>
    <link rel="stylesheet" href="{% static 'css/styles_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles_task_list.css' %}">
</head>
<body class="body">
    <header class="header">
        <nav class="nav">
            <a class="nav__link" href="{% url 'home' %}">Inicio</a>
            <a class="nav__link" href="{% url 'project_list' %}">Mis Proyectos</a>
            <a class="nav__link" href="{% url 'project_create' %}">Crear Nuevo Proyecto</a>
            <a class="nav__link" href="{% url 'task_create' %}">Crear Nueva Tarea</a>
            <form id="logout-form" method="post" action="/logout/">
                {% csrf_token %}
                <button class="nav__link btn__session" type="submit">Cerrar Sesión</button>
            </form>
        </nav>
    </header>

    <div class="chart">
        <canvas class="chart__pie" id="done_porcentaje" width="500" height="500"></canvas>
    </div>

    <main class="main">
        <section class="main__tasks">
            <h1 class="tasks__title">Tareas</h1>
            <div class="tasks__task">
                <!-- Mostramos las tareas -->
                {% for task in tasks %}
                    <article>
                        <h2>{{ task.title }}</h2>
                        <h3>{{ task.description }}</h3>
                        <p>Proyecto: {{ task.project.title }}</p>
                        <p>Descripción: {{ task.project.description }}</p>
                        <p>Creado en: {{ task.project.created_at }}</p>
                        <p>Fecha límite: {{ task.project.deadline }}</p>
                        <p>Estado: {{ task.get_status_display }}</p>
                        <div class="task__status">
                            <!-- Dependiendo del estado de la tarea, se muestra un botón u otro para 
                             cambiar el estod del proyecto -->
                            {% if task.status != 'TODO' %}
                                <form action="{% url 'task_status' task.id 'TODO' %}" method="post">
                                    {% csrf_token %}
                                    <button class="task__btn task__todo" type="submit">Pendiente</button>
                                </form>
                            {% endif %}
                            {% if task.status != 'IN_PROGRESS' %}
                                <form action="{% url 'task_status' task.id 'IN_PROGRESS' %}" method="post">
                                    {% csrf_token %}
                                    <button class="task__btn task__inprog" type="submit">En Progreso</button>
                                </form>
                            {% endif %}
                            {% if task.status != 'DONE' %}
                                <form action="{% url 'task_status' task.id 'DONE' %}" method="post">
                                    {% csrf_token %}
                                    <button class="task__btn task__done" type="submit">Terminada</button>
                                </form>
                            {% endif %}
                        </div>
                        <p>Prioridad: {{ task.get_priority_display }}</p>
                        <p>Creador: {{ task.project.owner }}</p>
                        <p>Colaboradores: 
                            <!-- Mostramos los colaboradores del proyecto asociado a la tarea -->
                            {% for collaborator in task.project.collaborators.all %}
                                {{ collaborator }} 
                            {% empty %}
                                No hay colaboradores
                            {% endfor %}
                        </p>
                        <p>Asignada a: {{ task.assigned_to }}</p>
                        <!-- Si el usuario es el creador del proyecto relacionado a la tarea se le muestran las acciones de editar 
                         y eliminar la tarea -->
                        {% if task.project.owner == user %}
                            <div class="task__actions">
                                <form action="/projects/tasks/update/{{ task.id }}" method="get">
                                    {% csrf_token %}
                                    <button class="task__btn task__update" type="submit">Editar Tarea</button>
                                </form>
                                <form action="/tasks/delete/{{ task.id }}" method="get">
                                    {% csrf_token %}
                                    <button class="task__btn task__delete" type="submit">Eliminar Tarea</button>
                                </form>
                            </div>
                        {% endif %}
                    </article>
                {% endfor %}
            </div>
        </section>

        <section class="back">
            <a class="back__link" href="{% url 'project_list' %}">VOLVER</a>
        </section>
    </main>
    
    <script>
        done_tasks = {{ done_tasks }}
    not_done_tasks = 100 - done_tasks
    </script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.2.1/dist/chart.umd.min.js"></script>
    <script src="{% static 'js/pie_chart.js' %}"></script>
</body>
</html>

taskmaster/templates/task_update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar Tarea</title>
    <link rel="stylesheet" href="{% static 'css/styles_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles_form.css' %}">
</head>
<body class="body">
    <header class="header">
        <nav class="nav">
            <a class="nav__link" href="{% url 'home' %}">Inicio</a>
            <a class="nav__link" href="{% url 'project_list' %}">Mis Proyectos</a>
            <a class="nav__link" href="{% url 'project_create' %}">Crear Nuevo Proyecto</a>
            <a class="nav__link" href="{% url 'task_create' %}">Crear Nueva Tarea</a>
            <form id="logout-form" method="post" action="/logout/">
                {% csrf_token %}
                <button class="nav__link btn__session" type="submit">Cerrar Sesión</button>
            </form>
        </nav>
    </header>

    <main class="main">
        <h1 class="main__title">Editar Tarea</h1>
        <form class="main__form" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="form__btn" type="submit">Editar Tarea</button>
        </form>
    </main>

    <section class="back">
        <a class="back__link" href="{% url 'task_list' object.project.id %}">VOLVER</a>
    </section>
</body>
</html>